[build]
  command = "npm run build"
  publish = "dist"

# Proxy /api requests to your EC2 Backend
[[redirects]]
  from = "/api/*"
  to = "http://54.193.34.134/api/:splat"
  status = 200
  force = true